# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 531)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_de = QtWidgets.QPushButton(self.centralwidget)
        self.btn_de.setGeometry(QtCore.QRect(330, 420, 93, 28))
        self.btn_de.setObjectName("btn_de")
        self.btn_en_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_en_2.setGeometry(QtCore.QRect(600, 420, 93, 28))
        self.btn_en_2.setObjectName("btn_en_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(480, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_plain_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_2.setGeometry(QtCore.QRect(590, 120, 301, 91))
        self.txt_plain_2.setObjectName("txt_plain_2")
        self.btn_de_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_de_2.setGeometry(QtCore.QRect(790, 420, 93, 28))
        self.btn_de_2.setObjectName("btn_de_2")
        self.btn_en = QtWidgets.QPushButton(self.centralwidget)
        self.btn_en.setGeometry(QtCore.QRect(150, 420, 93, 28))
        self.btn_en.setObjectName("btn_en")
        self.txt_cipher = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher.setGeometry(QtCore.QRect(150, 280, 301, 91))
        self.txt_cipher.setObjectName("txt_cipher")
        self.txt_cipher_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_2.setGeometry(QtCore.QRect(590, 280, 301, 91))
        self.txt_cipher_2.setObjectName("txt_cipher_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 270, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btn_en_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_en_3.setGeometry(QtCore.QRect(490, 50, 93, 28))
        self.btn_en_3.setObjectName("btn_en_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 30, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_plain = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain.setGeometry(QtCore.QRect(150, 120, 301, 91))
        self.txt_plain.setObjectName("txt_plain")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(470, 270, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_de.setText(_translate("MainWindow", "Decrypt"))
        self.btn_en_2.setText(_translate("MainWindow", "Sign"))
        self.label_2.setText(_translate("MainWindow", "Information"))
        self.label.setText(_translate("MainWindow", "PlainText"))
        self.btn_de_2.setText(_translate("MainWindow", "Verify"))
        self.btn_en.setText(_translate("MainWindow", "Encrypt"))
        self.label_3.setText(_translate("MainWindow", "CipherText"))
        self.btn_en_3.setText(_translate("MainWindow", "Genarete Keys"))
        self.label_4.setText(_translate("MainWindow", "RSA_CIPHER"))
        self.label_5.setText(_translate("MainWindow", "Signature"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
